/**
 * CockroachDB auth schema — Better Auth canonical shape, generated by
 * `@better-auth/cli generate` against an `anonymous()`-enabled config,
 * then adapted to:
 *
 *   - `cockroach-core` instead of `pg-core` (Drizzle dialect)
 *   - Added `crdb_region` column on every regional table for
 *     REGIONAL BY ROW locality (set in migration SQL — Drizzle can't
 *     model LOCALITY clauses)
 *
 * Regenerate canonically by running (from this directory):
 *
 *   pnpm db:gen:ba           # writes /tmp/ba-schema.ts via the BA CLI
 *
 * The auth.gen.ts file is the source-of-truth for "which BA plugins
 * we want a schema for." Add plugins there + re-run to pick up new
 * tables/columns.
 *
 * BA-required tables included:
 *   - user           (with isAnonymous from anonymous() plugin)
 *   - session        (BA's database-backed sessions — unused while
 *                    USE_STATELESS_SESSION=1, but the table is here so
 *                    the schema matches BA's canonical shape)
 *   - account        (email/password + OAuth)
 *   - verification   (forget-password, email-verification tokens)
 *
 * Anonymous users still have a non-null email — BA generates a
 * synthetic value (e.g. `temp-<id>@<domain>`) when isAnonymous=true.
 * No partial unique index needed.
 */
import { sql } from "drizzle-orm";
import { cockroachTable, cockroachEnum, text, timestamp, boolean, index } from "drizzle-orm/cockroach-core";

/**
 * `crdb_internal_region` is system-managed — CRDB creates it
 * automatically when you `ALTER DATABASE ... ADD REGION`. Declared
 * here only so Drizzle has a TS type for the column; drizzle-kit
 * doesn't generate a CREATE TYPE (the enum is owned by the database).
 */
export const crdbInternalRegion = cockroachEnum("crdb_internal_region", [
    "aws-us-east-2",
    "aws-eu-central-1",
    "aws-ap-southeast-1",
]);

const closestCrdbRegionFromGatewaySql = sql`default_to_database_primary_region(gateway_region())::crdb_internal_region`;

// ───── user ────────────────────────────────────────────────────────
// Note: BA emits singular table names (`user`, `session`, `account`,
// `verification`). Kept that way for schema parity.
export const user = cockroachTable("user", {
    id: text("id").primaryKey(),
    crdbRegion: crdbInternalRegion("crdb_region").notNull().default(closestCrdbRegionFromGatewaySql),
    name: text("name").notNull(),
    // Always non-null — anonymous users get a synthetic email from BA.
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").notNull().default(false),
    image: text("image"),
    // From the anonymous() plugin. Flips to false when the user
    // upgrades to a real account by adding email/password later.
    isAnonymous: boolean("is_anonymous").default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
        .notNull()
        .defaultNow()
        .$onUpdate(() => new Date()),
});

// ───── session ─────────────────────────────────────────────────────
// Present for BA-schema-compat but unused at runtime (stateless cookies).
export const session = cockroachTable(
    "session",
    {
        id: text("id").primaryKey(),
        crdbRegion: crdbInternalRegion("crdb_region").notNull(),
        userId: text("user_id").notNull(),
        token: text("token").notNull().unique(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .$onUpdate(() => new Date()),
    },
    table => [index("session_userId_idx").on(table.userId)]
);

// ───── account ─────────────────────────────────────────────────────
export const account = cockroachTable(
    "account",
    {
        id: text("id").primaryKey(),
        crdbRegion: crdbInternalRegion("crdb_region").notNull(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),
        userId: text("user_id").notNull(),
        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
        scope: text("scope"),
        password: text("password"),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .$onUpdate(() => new Date()),
    },
    table => [index("account_userId_idx").on(table.userId)]
);

// ───── verification ────────────────────────────────────────────────
// Forget-password tokens, email-verification tokens, magic-link tokens.
// Not regional — a verification is short-lived and not user-bound by
// region (the user may not exist yet). LOCALITY GLOBAL is appropriate
// but we leave the default for now; promote when traffic warrants it.
export const verification = cockroachTable(
    "verification",
    {
        id: text("id").primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow()
            .$onUpdate(() => new Date()),
    },
    table => [index("verification_identifier_idx").on(table.identifier)]
);

// ───── types ───────────────────────────────────────────────────────
// Drizzle 1.0.0-rc.3 reorganised the `relations` export; we don't need
// the relational query DSL because the adapter does explicit joins, so
// the `relations()` declarations BA's CLI emits are intentionally
// omitted. Re-add via `drizzle-orm/relations` if you switch to RQB.

export type User = typeof user.$inferSelect;
export type Session = typeof session.$inferSelect;
export type Account = typeof account.$inferSelect;
export type Verification = typeof verification.$inferSelect;
