/* eslint-disable */
// Generated by `wrangler types`. This Next.js app is the frontend only —
// it doesn't bind DOs/KV/D1 directly. Auth requests are proxied to the
// Hono auth Worker (see next.config.ts).

interface CloudflareEnv {
    ASSETS: Fetcher;
}
