/* eslint-disable */
// Generated by `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`.
// Regenerate after changing wrangler.toml bindings.

interface CloudflareEnv {
    USER_DO: DurableObjectNamespace;
    IDENTITY_DO: DurableObjectNamespace;
    KV: KVNamespace;
    AUTH_DB?: D1Database;
    ASSETS: Fetcher;
    GOOGLE_CLIENT_ID?: string;
    GOOGLE_CLIENT_SECRET?: string;
}
