/* eslint-disable */
// Generated by `wrangler types`. This Next.js app is the frontend only —
// it doesn't bind DOs/KV/D1 directly. Auth requests are proxied to the
// Hono auth Worker via the AUTH_BACKEND service binding (see
// wrangler.toml and src/middleware.ts).

interface CloudflareEnv {
    ASSETS: Fetcher;
    AUTH_BACKEND?: Fetcher;
}
