-- Migrate to Better Auth's canonical schema (generated by
-- @better-auth/cli generate, then adapted for CRDB REGIONAL BY ROW).
--
-- Changes vs the original 0000_init:
--   - Singular table names (user/session/account/verification) — BA standard
--   - Text id columns (BA generates string ids, not UUIDs)
--   - email is NOT NULL UNIQUE (anonymous users get synthetic emails)
--   - Added is_anonymous flag (from anonymous() plugin)
--   - Added session + verification tables (BA-required for completeness)
--   - Account FK references user (BA-canonical)
--
-- This migration DROPS the old tables. We assume no real data yet
-- (this PR is pre-launch). If you have real data, do an explicit data
-- migration first.

DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ───── user ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "user" (
    id              TEXT PRIMARY KEY,
    crdb_region     crdb_internal_region NOT NULL
                    DEFAULT default_to_database_primary_region(gateway_region())::crdb_internal_region,
    name            TEXT NOT NULL,
    email           TEXT NOT NULL UNIQUE,
    email_verified  BOOL NOT NULL DEFAULT false,
    image           TEXT,
    is_anonymous    BOOL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE "user" SET LOCALITY REGIONAL BY ROW;

-- ───── session ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "session" (
    id              TEXT PRIMARY KEY,
    crdb_region     crdb_internal_region NOT NULL,
    user_id         TEXT NOT NULL,
    token           TEXT NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    ip_address      TEXT,
    user_agent      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS session_userId_idx ON "session"(user_id);
ALTER TABLE "session" SET LOCALITY REGIONAL BY ROW;
ALTER TABLE "session"
    ADD CONSTRAINT session_user_id_fk
    FOREIGN KEY (user_id, crdb_region)
    REFERENCES "user" (id, crdb_region)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

-- ───── account ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "account" (
    id                          TEXT PRIMARY KEY,
    crdb_region                 crdb_internal_region NOT NULL,
    account_id                  TEXT NOT NULL,
    provider_id                 TEXT NOT NULL,
    user_id                     TEXT NOT NULL,
    access_token                TEXT,
    refresh_token               TEXT,
    id_token                    TEXT,
    access_token_expires_at     TIMESTAMPTZ,
    refresh_token_expires_at    TIMESTAMPTZ,
    scope                       TEXT,
    password                    TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS account_userId_idx ON "account"(user_id);
ALTER TABLE "account" SET LOCALITY REGIONAL BY ROW;
ALTER TABLE "account"
    ADD CONSTRAINT account_user_id_fk
    FOREIGN KEY (user_id, crdb_region)
    REFERENCES "user" (id, crdb_region)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

-- ───── verification ────────────────────────────────────────────────
-- Short-lived tokens. Not region-bound — a verification might be
-- created before a user exists. Default locality (regional-by-table
-- in the primary region) is fine.
CREATE TABLE IF NOT EXISTS "verification" (
    id              TEXT PRIMARY KEY,
    identifier      TEXT NOT NULL,
    value           TEXT NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON "verification"(identifier);
